#!/usr/bin/env bash
#Write a Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

function del_file() {
    rm /var/run/myscript.pid
    exit
}

trap 'echo "I hate the kill command";del_file' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'del_file' SIGQUIT
echo $$ >> /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
done
